-- Enable Row Level Security (RLS) is recommended, but for simplicity in this prototype we will start with public access
-- You can tighten security later by enabling RLS and adding policies.

-- 1. Game Settings Table (Stores global game state)
create table public.game_settings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_started boolean default false,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  target_percentage numeric,
  bet_amount numeric,
  payout_mode text
);

-- 2. Players Table
create table public.players (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  initial_weight numeric,
  current_weight numeric,
  target_weight numeric,
  weight_history jsonb default '[]'::jsonb, -- Storing array of {date, weight} objects
  cheers integer default 0,
  last_update_date timestamp with time zone,
  avatar_seed text,
  join_date timestamp with time zone,
  badges jsonb default '[]'::jsonb,
  streak integer default 0,
  bet_amount numeric
);

-- 3. Activity Logs Table
create table public.activity_logs (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text not null, -- 'JOIN', 'WEIGHT_UPDATE', 'CHEER', 'GAME_START'
  player_id bigint references public.players(id),
  player_name text,
  message text,
  timestamp timestamp with time zone,
  avatar_seed text
);

-- Enable Realtime for these tables
alter publication supabase_realtime add table public.game_settings;
alter publication supabase_realtime add table public.players;
alter publication supabase_realtime add table public.activity_logs;

-- Initial Game Settings Row (Ensure there is always one row to update)
insert into public.game_settings (id, is_started, payout_mode)
values (1, false, 'WINNER_TAKES_ALL')
on conflict (id) do nothing;
